# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-27 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ajout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
