# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-01 13:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_groupes', models.CharField(default='', max_length=45)),
                ('nom_utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_restaurant', models.CharField(max_length=45)),
                ('adresse_restaurant', models.CharField(max_length=45, unique=True)),
                ('ville_restaurant', models.CharField(max_length=45)),
                ('frequence', models.IntegerField(blank=True, null=True)),
                ('anciennete', models.DateField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, default=999)),
                ('image', models.ImageField(upload_to='images')),
                ('nom_groupes', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='index.Groupes')),
            ],
        ),
    ]
