# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-01 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20170201_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='nom_groupes',
            field=models.CharField(max_length=50),
        ),
    ]
