# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-01 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20170201_1700'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='restaurant',
            unique_together=set([('nom_groupes', 'adresse_restaurant')]),
        ),
    ]
