# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-02 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20170201_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='anciennete',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
