# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-03 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20170202_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupes',
            name='favori',
            field=models.BooleanField(default=False),
        ),
    ]
