# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-06 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_groupes_favori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='adresse_restaurant',
            field=models.CharField(max_length=45),
        ),
    ]
