# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-24 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20170206_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupes',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='anciennete',
            field=models.IntegerField(blank=True, default=10),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='frequence',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
