# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-24 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20170224_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupes',
            name='descriptif',
            field=models.CharField(default='', max_length=144),
        ),
    ]
